INSERT INTO PET (BREED_NAME, NAME_PET, TYPE_PET, GENDER, SIZE, VACCINATED, MICROCHIP, DOMESTIC, SOCIALITY, NEEDS_SPECIALITY, EXPERIENCE_ADOPT, PET_HISTORY, PET_DIET)
	VALUES ('Bulldog Francês', 'BILLY', 0, 0, 1, 2, 2, 2, 1, 0, 0, 'VITIMA DE MAUS TRATOS', 'SPECIAL DOG PRIME');
	
INSERT INTO PET (BREED_NAME, NAME_PET, TYPE_PET, GENDER, SIZE, VACCINATED, MICROCHIP, DOMESTIC, SOCIALITY, NEEDS_SPECIALITY, EXPERIENCE_ADOPT, PET_HISTORY, PET_DIET)
	VALUES ('Bulldog Francês', 'LILY', 0, 1, 1, 2, 2, 2, 1, 0, 0, 'VITIMA DE MAUS TRATOS', 'SPECIAL DOG PRIME');